build:
  version: "2.0"

accounts:
  message: "Hello from loan service"
  contactDetails:
    email: "devjangir_qa@gmail.com"
    name: "Dev Jangir"
  onCallSupports:
    - "8989898989"
    - "9898989898"